version: '2.0'

services:

  postgresql:
    image: quay.io/coreos/postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test

  elastisearch:
    image: quay.io/bitnami/elasticsearch:7
    ports:
      - "9200:9200"
